#!/usr/bin/env bash
# Installs nginx and configures it to serve "Holberton School for the win!"

apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx start
service nginx restart
