#!/usr/bin/env bash

# Install Nginx
apt-get update -y
apt-get install -y nginx

# Configure the default Nginx page
echo "Holberton School for the win!" > /var/www/html/index.html

# Start Nginx
service nginx start
