#!/usr/bin/env bash
# This script installs and configures Nginx to serve Holberton School

apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart
