#!/usr/bin/env bash

# Install and configure Nginx
apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

sed -i '/server_name _;/a\    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

service nginx restart
