#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to YouTube

sed -i 's|server_name _;|server_name _;\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }|' /etc/nginx/sites-available/default

service nginx restart
