#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to YouTube

sed -i '/server_name _;/a\
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }' /etc/nginx/sites-available/default

service nginx restart
